# Generated by Django 3.2 on 2022-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220602_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('casual', 0), ('auto', 1)], default=0),
        ),
        migrations.AlterField(
                model_name='boost',
                name='type',
                field=models.PositiveSmallIntegerField(choices=[(1, 'auto'), (0, 'casual')], default=0),
        ),
        migrations.AddField(
                model_name='core',
                name='auto_click_power',
                field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
                model_name='boost',
                name='type',
                field=models.PositiveSmallIntegerField(choices=[(0, 'casual'), (1, 'auto')], default=0),
        ),
    ]
